# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.0'
    checkLatest: true
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: '''sources Add -Name clouddsein -Source https://clouddsein.jfrog.io/artifactory/api/nuget/nuget -username amith -password ${{ parameters.ArtifactoryApiKey }}'''
    
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: '''setapikey amith:${{ parameters.ArtifactoryApiKey }} -Source clouddsein'''

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: '''restore ${{ parameters.SolutionPath }} -Source "$(NUGET_PACKAGES);https://clouddsein.jfrog.io/artifactory/api/nuget/nuget;http://www.nuget.org/api/v2/"'''
